apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-1
spec:
  storageClassName: faster-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-2
spec:
  storageClassName: faster-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi