version: "2"

services:
  
  nginx:
    image: nginx:1.14.0
    #image: nginx:alpine
    #build: ./nginx/
    #container_name: nginx-container
    ports:
      - "8000:80"
    volumes:
      - ./php/content:/srv/www/content
      - ./static:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    #links:
      #- php
      - nodejs

  nodejs:
    #image: node:alpine
    image: node:8.11.3
    #container_name: nodejs-container
    environment: 
      NODE_ENV: production
    working_dir: /home/app
    restart: always
    volumes:
      - ./nodejs:/home/app
    #depends_on:
    #links:
      #- php
      #- mongo
    command: ["node", "index"]

  #php:
    #image: php:apache
    #container_name: php-container
    #volumes:
      #- ./php:/var/www/html
    #depends_on:
    #links:
      #- mongo
  #mongo:
    #image: mongo:3.6
    #restart: always
    #environment: 
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: hosiana_Long
    #volumes:
    #- ./mongo-data:/data/db